// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebAPIBasics.Domains;

public partial class EmployeesDBContext : DbContext
{
    public EmployeesDBContext()
    {
    }

    public EmployeesDBContext(DbContextOptions<EmployeesDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblCrudTest> TblCrudTest { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-BCGHTML\\MSSQLSERVER2025;Initial Catalog=EmployeesDB;User ID=sa;Password=123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblCrudTest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tbl_crud__3214EC0742E1BE44");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}