// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPIBasics.Domains;

[Table("tbl_crud_test")]
public partial class TblCrudTest
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(250)]
    public string Email { get; set; }

    public bool IsDeleted { get; set; }
}